'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10.11.100.3")>  _
        Public Property Servidor() As String
            Get
                Return CType(Me("Servidor"),String)
            End Get
            Set
                Me("Servidor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SALUD_TEST")>  _
        Public Property BaseDeDatos() As String
            Get
                Return CType(Me("BaseDeDatos"),String)
            End Get
            Set
                Me("BaseDeDatos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Integral_test..")>  _
        Public Property BaseDatosIntegral() As String
            Get
                Return CType(Me("BaseDatosIntegral"),String)
            End Get
            Set
                Me("BaseDatosIntegral") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MasterProfitProA..")>  _
        Public Property BaseDatosMasterProfit() As String
            Get
                Return CType(Me("BaseDatosMasterProfit"),String)
            End Get
            Set
                Me("BaseDatosMasterProfit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-12")>  _
        Public Property CantMesesMorbilidad() As String
            Get
                Return CType(Me("CantMesesMorbilidad"),String)
            End Get
            Set
                Me("CantMesesMorbilidad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\10.11.201.10\BackupExportCss\")>  _
        Public Property ExportMañongoDirBackup() As String
            Get
                Return CType(Me("ExportMañongoDirBackup"),String)
            End Get
            Set
                Me("ExportMañongoDirBackup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\10.11.100.3\BDManongoExportada\")>  _
        Public Property ExportMañongoDirRestaurar() As String
            Get
                Return CType(Me("ExportMañongoDirRestaurar"),String)
            End Get
            Set
                Me("ExportMañongoDirRestaurar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PRE001")>  _
        Public Property CoColorProductos_Tarjetas() As String
            Get
                Return CType(Me("CoColorProductos_Tarjetas"),String)
            End Get
            Set
                Me("CoColorProductos_Tarjetas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CargarDetalleDocumentoOrigenCrearNotas() As String
            Get
                Return CType(Me("CargarDetalleDocumentoOrigenCrearNotas"),String)
            End Get
            Set
                Me("CargarDetalleDocumentoOrigenCrearNotas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SERV")>  _
        Public Property CoColorProductos_Servicios() As String
            Get
                Return CType(Me("CoColorProductos_Servicios"),String)
            End Get
            Set
                Me("CoColorProductos_Servicios") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10.11.100.3")>  _
        Public Property ServidorSedeCentral() As String
            Get
                Return CType(Me("ServidorSedeCentral"),String)
            End Get
            Set
                Me("ServidorSedeCentral") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("IPSS")>  _
        Public Property BaseDeDatosIPSS() As String
            Get
                Return CType(Me("BaseDeDatosIPSS"),String)
            End Get
            Set
                Me("BaseDeDatosIPSS") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB;Data Source=10.11.100.3;Persist Security Info=True;Password=pro"& _ 
            "fit;User ID=profit;Initial Catalog=Integral")>  _
        Public ReadOnly Property ConnectionString_Integral() As String
            Get
                Return CType(Me("ConnectionString_Integral"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB;Data Source=10.11.100.3;Password=profit;User ID=profit;Initial "& _ 
            "Catalog=Integral_Test")>  _
        Public ReadOnly Property ConnectionString_test() As String
            Get
                Return CType(Me("ConnectionString_test"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB;Data Source=10.11.100.3;Persist Security Info=True;Password=pro"& _ 
            "fit;User ID=profit;Initial Catalog=IPSS")>  _
        Public ReadOnly Property ConnectionString_IPSS() As String
            Get
                Return CType(Me("ConnectionString_IPSS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB;Data Source=10.11.100.3;Password=profit;User ID=profit;Initial "& _ 
            "Catalog=IPSS_FILES")>  _
        Public ReadOnly Property ConnectionString_IPSS_FILES() As String
            Get
                Return CType(Me("ConnectionString_IPSS_FILES"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SisSalud.My.MySettings
            Get
                Return Global.SisSalud.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
